import { z } from 'zod'

export const eventCategories = [
  'Scen',
  'Nattliv', 
  'Sport',
  'Utställningar',
  'Konst',
  'Föreläsningar',
  'Barn & Familj',
  'Mat & Dryck',
  'Jul',
  'Film & bio',
  'Djur & Natur',
  'Guidade visningar',
  'Marknader',
  'Okategoriserad'
] as const

export const eventStatuses = [
  'draft',
  'pending_approval',
  'published',
  'cancelled'
] as const

export const eventSchema = z.object({
  event_id: z.string().optional(), // Auto-generated by system
  name: z.string().min(1, 'Namn krävs'),
  description: z.string().optional().or(z.literal('')),
  date_time: z.string().min(1, 'Datum och tid krävs'),
  location: z.string().min(1, 'Adress krävs'),
  venue_name: z.string().optional().or(z.literal('')), // Platsnamn
  price: z.string().optional().or(z.literal('')),
  image_url: z.string().url('Ogiltig URL').optional().or(z.literal('')),
  organizer_event_url: z.string().url('Ogiltig URL').optional().or(z.literal('')),
  // Support både gamla och nya kategori-systemet
  category: z.enum(eventCategories).optional(), // Deprecated: använd categories istället
  categories: z.array(z.enum(eventCategories)).min(1, 'Minst en kategori krävs').max(3, 'Max 3 kategorier'),
  organizer_id: z.number().optional(),
  featured: z.boolean(),
  status: z.enum(eventStatuses),
  max_participants: z.number().positive('Måste vara ett positivt tal').optional(),
  tags: z.array(z.string()),
})

export const organizerSchema = z.object({
  name: z.string().min(1, 'Namn krävs'),
  location: z.string().optional(),
  venue_name: z.string().optional().or(z.literal('')), // Platsnamn för organizer
  phone: z.string().optional(),
  email: z.string().email('Ogiltig e-postadress').optional().or(z.literal('')),
  website: z.string().url('Ogiltig URL').optional().or(z.literal('')),
})

export type EventFormData = z.infer<typeof eventSchema>
export type OrganizerFormData = z.infer<typeof organizerSchema>
